
mongo:
  restart: always
  image: tutum/mongodb
  volumes:
    - /data/db:/opt/db
  ports:
    - "27017:27017"
  environment:
    - MONGODB_DATABASE=mydatabase
    - MONGODB_USER=user
    - MONGODB_PASS=mypass
  command: /run.sh --smallfiles
  
thing-a-day:
  restart: always
  image: thing-a-day
  ports:
    - "3000:3000"
  environment:
    - MONGODB_DATABASE=mydatabase
    - MONGODB_USER=user
    - MONGODB_PASS=mypass 
    - MESSAGING_LOGIN=admin
    - MESSAGING_PASSWORD=admin 
    
    
  links:
    
  
    - mongo
  
  
    - activemq
  

activemq:
  restart: always
  image: webcenter/activemq
  ports:
    - "61613:61613"
  environment:
    - ACTIVEMQ_ADMIN_LOGIN=admin
    - ACTIVEMQ_ADMIN_PASSWORD=admin



